const { REACT_APP_EMAILJS_SERVICE_ID , REACT_APP_EMAILJS_TEMPLATE_ID , REACT_APP_EMAILJS_PUBLIC_KEY} = process.env;
export const environmentsVariables = {
    REACT_APP_EMAILJS_SERVICE_ID ,
REACT_APP_EMAILJS_TEMPLATE_ID, 
REACT_APP_EMAILJS_PUBLIC_KEY,
}